name: dast-zap

on:
  push:
    branches:
      - master
      - dev

jobs:

  zap_scan:
    runs-on: ubuntu-latest
    name: zap-proxy scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://jaliaga-app-vulnerable2022.herokuapp.com/'
          rules_file_name: ./api-scan.conf
