name: dast-zap

on:
  push:
    branches:
      - dev
#  workflow_call:
#    secrets:
#      HAWK_API_KEY:
#        required: true

jobs:
  DAST-API:
    name: ZAP API Scan
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3
      - name: ZAP Scan
        continue-on-error: true
        run: |
          docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-weekly zap-api-scan.py -t https://jaliaga-app-vulnerable2022.herokuapp.com/ -f openapi -c api-scan.conf
